import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:sqlite3/sqlite3.dart';

import 'database_key.dart';

/// Thrown when a database file exists but cannot be decrypted.
///
/// SQLCipher reports a wrong or missing key as `file is not a database`, which
/// is indistinguishable from genuine corruption and tells a driver nothing.
/// This exists so the app can recognise the case and say what actually
/// happened.
///
/// **Nothing recovers from this automatically.** Not a delete, not a recreate,
/// not a retry with a fresh key. Losing a week of settlements is bad; losing it
/// silently and then behaving as though nothing happened is unrecoverable,
/// because the driver has no reason to suspect the app rather than his own
/// memory. The only path out is a destructive reset the driver explicitly
/// confirms.
final class DatabaseUnreadableException implements Exception {
  const DatabaseUnreadableException(this.path, this.cause);

  /// The database file. A path, not its contents — nothing here is PII.
  final String path;

  /// What SQLite actually said, kept for a bug report.
  final Object cause;

  @override
  String toString() =>
      'DatabaseUnreadableException: the database at $path exists but could not '
      'be decrypted. The key is missing or wrong. Underlying error: $cause';
}

/// Opens the encrypted database at [file].
///
/// The key comes from [keys], which refuses to mint one when a database is
/// already on disk — see [DatabaseKeyProvider].
///
/// Key rotation and `PRAGMA rekey` are out of scope for the MVP. They belong
/// with the V2 sync work, where a key that has to be re-derived on a second
/// device is a real problem rather than a hypothetical one.
Future<QueryExecutor> openEncryptedDatabase({
  required File file,
  required DatabaseKeyProvider keys,
}) async {
  final bool exists = file.existsSync();
  final String key = await keys.obtain(databaseExists: exists);

  await file.parent.create(recursive: true);

  return NativeDatabase(
    file,
    setup: (Database database) => applyKey(database, key, file.path),
  );
}

/// Applies [key] and proves it worked.
///
/// `PRAGMA key` does not fail on a wrong key — it only sets one, and the
/// failure surfaces on the first page read. So this reads immediately rather
/// than letting a wrong key look like success until the first query somewhere
/// deep in the app.
void applyKey(Database database, String key, String path) {
  // Raw key form: no KDF, because the key was generated by a CSPRNG and never
  // typed by a human, so there is no weak input to stretch.
  database.execute('PRAGMA key = "x\'$key\'"');

  try {
    database.select('SELECT count(*) FROM sqlite_master');
  } on SqliteException catch (error) {
    throw DatabaseUnreadableException(path, error);
  }
}

/// Whether [file] holds a plaintext SQLite database.
///
/// Reads the 16-byte header. An encrypted file starts with ciphertext, so this
/// is false for anything SQLCipher wrote — which is exactly the assertion worth
/// making about a file full of Algerian households and the cash they are about
/// to receive.
bool looksLikePlaintextSqlite(File file) {
  if (!file.existsSync()) {
    return false;
  }
  final RandomAccessFile handle = file.openSync();
  try {
    final List<int> header = handle.readSync(16);
    return String.fromCharCodes(header).startsWith('SQLite format 3');
  } finally {
    handle.closeSync();
  }
}
